# xsltm_6.yaml
model:
  class_path: xlstm.model.XLSTM
  num_layers: 4
  input_dim: 128
  head_dim: 32
  num_heads: 4
  projection_factor: 2
  kernel_size: 4

tokenizer:
  path: 'openai-community/gpt2'
  special_tokens:
    pad_token: '<pad>'

optimizer:
  lr: 0.0001
  weight_decay: 0.01